#!/usr/bin/env python

def build(bld):
    bld(
        features='c cprogram',
        source = 'octonaut_tests.c',
        target = 'octonaut_tests',
        use = ['check', 'ev', 'gcov', 'octonaut'])
