#!/usr/bin/env python

def build(bld):
    bld(
        features='c cprogram',
        source = bld.path.ant_glob('*.c'),
        target = 'octonaut_tests',
        use = ['check', 'ev', 'octonaut'])
