#!/usr/bin/env python

def build(bld):
    bld.stlib(
        source = ['http_parser.c', 'http_request.c', 'http_server.c'],
        target = 'octohttp',
        use = ['ev', 'octonaut'],
        export_includes = [".", ".."])
