#!/usr/bin/env python

def build(bld):
    bld.stlib(
        source = ['buffer.c', 'logger.c', 'aio.c', 'server.c', 'hash_function.c'],
        target = 'octonaut',
        export_includes = [".", ".."])
